Fix spelling errors
CEO-Chair/HeadlessTerrariaClient pull request #8
Opened 2022-05-15 23:14 UTC by CEO-Chair

2022-05-20 23:36 UTC, CEO-Chair commented
i dont think its ready to be merged, i might need a second opinion

2022-05-23 00:53 UTC, CEO-Chair commented
seems to have some merge issues might fix later

2022-05-26 20:27 UTC, CEO-Chair commented
dont know if this is ready to be merged yet

2022-06-11 16:21 UTC, CEO-Chair commented
might fix later

2022-06-13 12:21 UTC, CEO-Chair commented
this might be ready to merge, still preparing main branch

2022-07-06 08:54 UTC, chairclr commented
guys can i get a code review

2022-07-06 08:55 UTC, hakusaro approved these changes

2022-07-06 08:57 UTC, hakusaro requested changes

2022-07-06 08:57 UTC, hakusaro commented on README.md
>    - World Data Recieved
Same issue here

2022-07-06 08:57 UTC, steviegt6 requested changes

2022-07-06 08:57 UTC, steviegt6 commented on README.md
> +  - Chat Message Received
```suggestion
  - Chat Message Received
```

2022-07-06 09:08 UTC, CEO-Chair commented on README.md
> +  - Chat Message Received
hi tomat

2022-07-08 02:43 UTC, CEO-Chair commented
no dsicrption proided

2022-07-08 03:28 UTC, steviegt6 commented
> no dsicrption proided

I see!

2022-07-17 23:23 UTC, steviegt6 commented on README.md
> +  - Chat Message Received
hi tomat

2023-02-10 04:27 UTC, CEO-Chair commented
hi

2023-02-10 18:33 UTC, steviegt6 commented
LBTM (looks bood to me)

2023-02-10 20:01 UTC, hakusaro commented
Lstm (looks Sarah to me)

2023-02-14 18:32 UTC, steviegt6 commented
LSTM (let's steal the monstitution)

2023-02-28 02:09 UTC, CEO-Chair commented
This PR sounds pretty cool. Any thoughts/

2023-02-28 06:17 UTC, hakusaro commented
@CEO-Chair thoughts: revoke

2023-02-28 06:19 UTC, CEO-Chair commented
hi

2023-03-05 08:22 UTC, steviegt6 commented
@CEO-Chair, can we get a review before merging? LGTM

2023-03-07 05:57 UTC, CEO-Chair commented
> can we get a review before merging?

yeah sure

2023-03-31 01:46 UTC, merged

2023-03-31 16:27 UTC, steviegt6 reviewed
LGTM